### ISSUE TITLE
Menu doesn't work after starting logseq

### ISSUE THREAD

**Issue by rubycornish** [haydenull/logseq-plugin-git#31]
Hi,

Thanks for writing the plugin. Makes synching a lot easier. However I have an issue where the menu doesn't work after starting logseq. The buttons are not visible and the menu is empty. I have to restart, sometimes a couple of times, before it appears again.

Screenshot attached.
![screenshot](https://user-images.githubusercontent.com/19799202/229055996-252b49d7-9633-47ac-940e-3fc50dfb8852.png)

Thanks!

**Comment by haydenull** [comment]
It seems that you might not have an enabled button in your settings. Please check your settings to ensure everything is properly configured.

<img width="1530" alt="image" src="https://user-images.githubusercontent.com/17695989/229262091-6392750e-253a-4803-b0c8-3a6a96c90c4f.png">

**Comment by passedpawn1986** [comment]
I'm also getting this issue.
![image](https://user-images.githubusercontent.com/49601821/231633105-49d7fda4-9d25-4607-9917-87abc539a827.png)
However, it won't work even after restarting the app.
I just get a scrollable area that will intermittently show the options if I scroll down, but more often than not it's just blank space.
![image](https://user-images.githubusercontent.com/49601821/231633283-2aed96b1-9aea-4b0c-8deb-21fd1f807ae7.png)

**Comment by haydenull** [comment]
Do you use custom CSS or any themes?

**Comment by passedpawn1986** [comment]
Not currently. I had been using a theme so I uninstalled it to check and still getting the same behaviour.
Currently just set to the dark theme included with logseq.
I don't have any custom CSS.

**Comment by rtmkrlv** [comment]
I have the same problem. Disabling all other plugins and using the standard theme does not change anything.  
![image](https://user-images.githubusercontent.com/8701534/231667129-e8ab6b2b-4ff9-4d5a-b6e9-c71245a648e8.png)

**Comment by Edandon** [comment]
Same here, Getting the scroll bar. 

Tried:
- disabling all themes.
- Restarting multiple times.

Still same result.

Only now appeared, sadly I haven't been paying enough attention to any plugin or app updates that may have marked the beginning of this issue.

**Comment by ItsFated** [comment]
I had the same problem after update to latest version. 2023-4-13 23:40:56

**Comment by ItsFated** [comment]
> 56

There is no other operation

**Comment by ItsFated** [comment]
> I had the same problem after update to latest version. 2023-4-13 23:40:56

There is no other operation

**Comment by haydenull** [comment]
Logseq version 0.9.2 has modified the style of the toolbar, which has affected the git panel as it is embed within it. To temporary fix this issue, you can add the following code in `custom.css`. The plugin's next version will is expected to address this problem.

```css
.ui-items-container[data-type=toolbar]>.list-wrap {
  overflow: visible;
}
```

**Comment by wtanksleyjr** [comment]
I have nothing in my custom.css apart from pasting that suggested workaround in. It doesn't make the git button work, unfortunately - it changes the behavior so that instead of showing what others depicted above, it drops down a tiny box containing nothing (too small to contain much).

I do have options checked in my settings, so something should be in there.

GREAT plugin, I'm crossing my fingers for the release.

**Comment by haydenull** [comment]
The plugin DOM structure has bee re-modified in version 1.5.1 , you can try it again.

**Comment by Edandon** [comment]
Can confirm that at least for me 1.5.1 solved the issue.

Cheers

**Comment by wtanksleyjr** [comment]
Worked for me too -- thank you!

**Comment by lef-est** [comment]
> The plugin DOM structure has bee re-modified in version 1.5.1 , you can try it again.

@haydenull after 1.5.1 this plugin works again but i started having problems with logseq's main view (or maybe sidebar too, i can't remember) losing focus very often, and i have to click on it to get its focus back. when that happens, i notice the only element i can select via the devtools is the `plugin-git-mask`, so i'm suspecting this is the cause. if it is indeed caused by this plugin, could there perhaps be a better workaround? 😆

**Comment by haydenull** [comment]
May I know which version of logseq are you using? Please try restarting logseq and see if it works. @lef-est

**Comment by rtmkrlv** [comment]
> losing focus very often

Faced with the same problem. Reproduced on versions Logseq 0.9.2 and 0.9.3. I use the standard theme, with only Git plugin enabled.

**Comment by haydenull** [comment]
does "losing focus" means that clicking anywhere doesn't respond? Also, Is the computer experiences this issue a Mac or a Windows computer? Will the issue still persist after restating logseq?

**Comment by rtmkrlv** [comment]
> does "losing focus" means that clicking anywhere doesn't respond?

No. Losing focus means that, for example, in order to edit a line, you must first click anywhere in the Logseq window to bring it back into focus, and then click again to edit the line. That is, instead of one click, you have to do two. This was not the case before Logseq 0.9.2.

> Also, Is the computer experiences this issue a Mac or a Windows computer?

I use Windows 11.

> Will the issue still persist after restating logseq?

Restarting has no effect. The problem occurs all the time after updating Logseq to 0.9.2.

**Comment by lef-est** [comment]
I can't say if it's logseq 0.9.2's bug or this plugin's bug, but I only started noticing it after I updated this plugin to 0.5.1, and frequently had devtools selecting the `plugin-git-mask` as the top element. Windows 10 here.

**Comment by haydenull** [comment]
The version 1.5.2 has just been release. please update the plugin , restart logseq and see if the problem persists.

**Comment by rtmkrlv** [comment]
The problem seems to have been solved. After updating the plugin to 1.5.2 the focus was no longer lost. Thank you.

**Comment by ayamir** [comment]
This issue still here on Linux.
![image](https://user-images.githubusercontent.com/61657399/235819186-15601fdd-8c60-47c1-8f48-0c8cfd5354ea.png)

**Comment by lef-est** [comment]
I think it's fixed too! :heart:

**Comment by mateuszkochanek** [comment]
Hi! After updating to v1.5.5 I am getting this error. Menu with buttons does not show up after clicking the plugin icon. I am using standard theme. Reproduced on both Windows 11 and Arch linux.

**Comment by haydenull** [comment]
> Hi! After updating to v1.5.5 I am getting this error. Menu with buttons does not show up after clicking the plugin icon. I am using standard theme. Reproduced on both Windows 11 and Arch linux.

@mateuszkochanek May I ask which version of logseq you are using?

**Comment by mateuszkochanek** [comment]
@haydenull Sorry for bothering you, I just realized that I didn't update logseq on Arch - thats why it didn't work. On Windows it was the other way, it didn't work because I updated logseq, but didn't have newest version of your plugin. 
So all in all it was all due to my oversight.
